"""add_unique_constraints_answers

Revision ID: 00578d1644f4
Revises: b765340100b6
Create Date: 2025-12-21 15:20:53.473126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00578d1644f4'
down_revision: Union[str, Sequence[str], None] = 'b765340100b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_unique_selected_option', 'user_answers', ['response_id', 'question_id', 'selected_option_id'], unique=True, postgresql_where=sa.text('selected_option_id IS NOT NULL'))
    op.create_index('idx_unique_text_answer', 'user_answers', ['response_id', 'question_id'], unique=True, postgresql_where=sa.text('text_answer IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_text_answer', table_name='user_answers', postgresql_where=sa.text('text_answer IS NOT NULL'))
    op.drop_index('idx_unique_selected_option', table_name='user_answers', postgresql_where=sa.text('selected_option_id IS NOT NULL'))
    # ### end Alembic commands ###
