"""initial_base

Revision ID: 540fa1a9b90f
Revises: 
Create Date: 2025-12-22 18:38:52.335502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '540fa1a9b90f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('user', 'creator', 'admin', name='user_role_enum'), nullable=False),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('birth_date < CURRENT_DATE', name='check_birth_date'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_login', 'users', ['email'], unique=False, postgresql_include=['password_hash', 'user_id', 'role'])
    op.create_table('surveys',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'archived', name='survey_status'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_date > start_date', name='check_dates'),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('survey_id')
    )
    op.create_index('idx_active_surveys', 'surveys', ['created_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_surveys_author_id'), 'surveys', ['author_id'], unique=False)
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('single_choice', 'multiple_choice', 'text_answer', 'rating', name='question_type_enum'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.survey_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_survey_id'), 'questions', ['survey_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Interval(), sa.Computed('completed_at - started_at', persisted=True), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.CheckConstraint('completed_at >= started_at', name='check_completion_time'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.survey_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('response_id'),
    sa.UniqueConstraint('survey_id', 'user_id', name='unique_user_survey_attempt')
    )
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_user_id'), 'survey_responses', ['user_id'], unique=False)
    op.create_table('survey_tags',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.survey_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('survey_id', 'tag_id')
    )
    op.create_table('options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_table('user_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.CheckConstraint('selected_option_id IS NOT NULL OR text_answer IS NOT NULL', name='check_answer_content'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['survey_responses.response_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['options.option_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index('idx_answers_analytics', 'user_answers', ['question_id', 'selected_option_id'], unique=False)
    op.create_index('idx_unique_selected_option', 'user_answers', ['response_id', 'question_id', 'selected_option_id'], unique=True, postgresql_where=sa.text('selected_option_id IS NOT NULL'))
    op.create_index('idx_unique_text_answer', 'user_answers', ['response_id', 'question_id'], unique=True, postgresql_where=sa.text('text_answer IS NOT NULL'))
    # ### end Alembic commands ###

    op.execute("""
    CREATE OR REPLACE FUNCTION get_survey_recommendations(p_user_id INT)
    RETURNS TABLE (survey_id INT, match_score BIGINT) AS $$
    BEGIN
        RETURN QUERY
        WITH user_tags AS (
            SELECT DISTINCT st.tag_id
            FROM survey_responses sr
            JOIN survey_tags st ON sr.survey_id = st.survey_id
            WHERE sr.user_id = p_user_id AND sr.completed_at IS NOT NULL
        )
        SELECT 
            s.survey_id,
            COUNT(st.tag_id) as score
        FROM surveys s
        JOIN survey_tags st ON s.survey_id = st.survey_id
        WHERE s.status = 'active'
          AND s.survey_id NOT IN (
              SELECT sr.survey_id FROM survey_responses sr WHERE sr.user_id = p_user_id
          )
          AND st.tag_id IN (SELECT tag_id FROM user_tags)
        GROUP BY s.survey_id
        ORDER BY score DESC, s.created_at DESC
        LIMIT 10;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE OR REPLACE FUNCTION search_surveys_ranked(p_query TEXT)
    RETURNS TABLE (survey_id INT, search_rank REAL) AS $$
    BEGIN
        RETURN QUERY
        SELECT 
            s.survey_id,
            ts_rank(
                setweight(to_tsvector('russian', s.title), 'A') || 
                setweight(to_tsvector('russian', coalesce(s.description, '')), 'B'),
                plainto_tsquery('russian', p_query)
            ) AS rank
        FROM surveys s
        WHERE to_tsvector('russian', s.title || ' ' || coalesce(s.description, '')) @@ plainto_tsquery('russian', p_query)
          AND s.status = 'active'
        ORDER BY rank DESC;
    END;
    $$ LANGUAGE plpgsql;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP FUNCTION IF EXISTS get_survey_recommendations(INT);")
    op.execute("DROP FUNCTION IF EXISTS search_surveys_ranked(TEXT);")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_text_answer', table_name='user_answers', postgresql_where=sa.text('text_answer IS NOT NULL'))
    op.drop_index('idx_unique_selected_option', table_name='user_answers', postgresql_where=sa.text('selected_option_id IS NOT NULL'))
    op.drop_index('idx_answers_analytics', table_name='user_answers')
    op.drop_table('user_answers')
    op.drop_table('options')
    op.drop_table('survey_tags')
    op.drop_index(op.f('ix_survey_responses_user_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_questions_survey_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_surveys_author_id'), table_name='surveys')
    op.drop_index('idx_active_surveys', table_name='surveys', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('surveys')
    op.drop_index('idx_user_login', table_name='users', postgresql_include=['password_hash', 'user_id', 'role'])
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('countries')
    # ### end Alembic commands ###
