"""Initial migration

Revision ID: b765340100b6
Revises: 
Create Date: 2025-12-16 23:21:05.496573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b765340100b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs_2024')
    op.drop_table('audit_logs_2025')
    op.drop_table('audit_logs')
    op.alter_column('options', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_questions_survey_id'), 'questions', ['survey_id'], unique=False)
    op.alter_column('survey_responses', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('survey_responses', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_user_id'), 'survey_responses', ['user_id'], unique=False)
    op.alter_column('surveys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_surveys_description_gin'), table_name='surveys', postgresql_using='gin')
    op.create_index('idx_active_surveys', 'surveys', ['created_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_surveys_author_id'), 'surveys', ['author_id'], unique=False)
    op.alter_column('user_answers', 'response_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_answers_analytics', 'user_answers', ['question_id', 'selected_option_id'], unique=False)
    op.create_index('idx_user_login', 'users', ['email'], unique=False, postgresql_include=['password_hash', 'user_id', 'role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_login', table_name='users', postgresql_include=['password_hash', 'user_id', 'role'])
    op.drop_index('idx_answers_analytics', table_name='user_answers')
    op.alter_column('user_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_answers', 'response_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_surveys_author_id'), table_name='surveys')
    op.drop_index('idx_active_surveys', table_name='surveys', postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('idx_surveys_description_gin'), 'surveys', [sa.literal_column("to_tsvector('russian'::regconfig, description)")], unique=False, postgresql_using='gin')
    op.alter_column('surveys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_survey_responses_user_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.alter_column('survey_responses', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('survey_responses', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_questions_survey_id'), table_name='questions')
    op.alter_column('questions', 'survey_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('options', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('audit_logs_2025',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('audit_logs_2024',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
